### ISSUE TITLE
Cannot create wrapped image in C API

### ISSUE THREAD

**Issue by giapvn** [NVIDIA/nvImageCodec#3]
### Describe the question.

I am trying to test C API on Ubuntu 22.04 with CPU x86_64 architecture and CUDA 12.2 following [this example](https://docs.nvidia.com/cuda/nvimagecodec/samples/c_samples.html#single-image-decode). However, I faced an issue at step 5 as below:
```
nvimgcodecImage_t image;
nvimgcodecImageCreate(instance, &image, &image_info)
```
`nvimgcodecImageCreate()` function returned status of `NVIMGCODEC_STATUS_INVALID_PARAMETER`
Can anyone support me on this problem?
Thanks all.

### Check for duplicates

- [x] I have searched the [open bugs/issues](https://github.com/NVIDIA/nvImageCodec/issues) and have found no duplicates for this bug report

**Comment by jantonguirao** [comment]
Hi @giapvn. To better help you with this, could you provided the whole code snippet you are compiling/running? Thanks

**Comment by giapvn** [comment]
Thanks @jantonguirao. I fixed the errors in my code. It is a wrong instance in `image_info` propagated into.

**Comment by jantonguirao** [comment]
Perfect. Thanks for letting us know. I will close the issue then.
